--DROPS
DROP TABLE tabela_anchor;
DROP TABLE tabela_historico;
DROP TABLE tabela_ocupacao;
DROP TABLE tabela_moto;
DROP TABLE tabela_vaga;

--CREATES
--TABElA VAGA
CREATE TABLE tabela_vaga (
    id_vaga       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo        VARCHAR2(10) UNIQUE NOT NULL, -- Ex: A01, B05, C12
    x_coord       NUMBER(10,2) NOT NULL,        -- coordenada X do canto inferior
    y_coord       NUMBER(10,2) NOT NULL,        -- coordenada Y do canto inferior
    largura       NUMBER(10,2) NOT NULL,
    altura        NUMBER(10,2) NOT NULL
);

--TABELA MOTO
CREATE TABLE tabela_moto (
    id_moto     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_id      VARCHAR2(20) UNIQUE NOT NULL, -- Ex: TAG_001
    placa       VARCHAR2(7) UNIQUE NOT NULL
);

--TABELA OCUPAÇÃO
CREATE TABLE tabela_ocupacao (
    id_ocupacao  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_vaga      INTEGER NOT NULL,
    id_moto      INTEGER NOT NULL,
    dt_ocupacao  DATE NOT NULL,
    CONSTRAINT id_vaga_ocupacao_fk FOREIGN KEY (id_vaga) REFERENCES tabela_vaga(id_vaga),
    CONSTRAINT id_moto_ocupacao_fk FOREIGN KEY (id_moto) REFERENCES tabela_moto(id_moto)
);

--TABELA HISTÓRICO
CREATE TABLE tabela_historico (
    id_evento    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_moto      NUMBER NOT NULL,
    id_vaga      NUMBER NOT NULL,
    acao         VARCHAR2(20) NOT NULL, -- 'ENTRADA', 'SAIDA', 'MUDANCA'
    dt_evento    DATE NOT NULL,
    CONSTRAINT id_vaga_historico_fk FOREIGN KEY (id_vaga) REFERENCES tabela_vaga(id_vaga),
    CONSTRAINT id_moto_historico_fk FOREIGN KEY (id_moto) REFERENCES tabela_moto(id_moto),
    CONSTRAINT chk_acao CHECK (acao IN ('ENTRADA', 'SAIDA', 'MUDANCA')) 
);

--TABELA ANCHOR
CREATE TABLE tabela_anchor (
    id_anchor   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      VARCHAR2(10) UNIQUE NOT NULL, -- Ex: A01, A02
    x_coord     NUMBER(10,2) NOT NULL,
    y_coord     NUMBER(10,2) NOT NULL
);

--INSERTS
--MOTOS
INSERT INTO tabela_moto (id_moto, tag_id, placa) VALUES (1, 'TAG_001', 'KXZ4J72');
INSERT INTO tabela_moto (id_moto, tag_id, placa) VALUES (2, 'TAG_002', 'FQW2H19');
INSERT INTO tabela_moto (id_moto, tag_id, placa) VALUES (3, 'TAG_003', 'BRL7M85');
INSERT INTO tabela_moto (id_moto, tag_id, placa) VALUES (4, 'TAG_004', 'TXP1C43');
INSERT INTO tabela_moto (id_moto, tag_id, placa) VALUES (5, 'TAG_005', 'MHD6Z10');
INSERT INTO tabela_moto (id_moto, tag_id, placa) VALUES (6, 'TAG_006', 'QGV9B27');
INSERT INTO tabela_moto (id_moto, tag_id, placa) VALUES (7, 'TAG_007', 'PLS3D91');
INSERT INTO tabela_moto (id_moto, tag_id, placa) VALUES (8, 'TAG_008', 'ZRT8F64');
INSERT INTO tabela_moto (id_moto, tag_id, placa) VALUES (9, 'TAG_009', 'VKC5H02');
INSERT INTO tabela_moto (id_moto, tag_id, placa) VALUES (10, 'TAG_010', 'JWM7R88');
INSERT INTO tabela_moto (id_moto, tag_id, placa) VALUES (11, 'TAG_011', 'LHF2P30');
INSERT INTO tabela_moto (id_moto, tag_id, placa) VALUES (12, 'TAG_012', 'CGY4N57');
INSERT INTO tabela_moto (id_moto, tag_id, placa) VALUES (13, 'TAG_013', 'DRX1V09');
INSERT INTO tabela_moto (id_moto, tag_id, placa) VALUES (14, 'TAG_014', 'SBM6T82');
INSERT INTO tabela_moto (id_moto, tag_id, placa) VALUES (15, 'TAG_015', 'HQA9K15');

--VAGAS
-- Fileira A
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (1, 'A01', 1.4, 1.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (2, 'A02', 2.5, 1.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (3, 'A03', 3.6, 1.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (4, 'A04', 4.7, 1.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (5, 'A05', 5.8, 1.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (6, 'A06', 6.9, 1.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (7, 'A07', 8.0, 1.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (8, 'A08', 9.1, 1.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (9, 'A09', 10.2, 1.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (10, 'A10', 11.3, 1.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (11, 'A11', 12.4, 1.4, 2, 1.1);

-- Fileira B
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (12, 'B01', 1.4, 4.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (13, 'B02', 2.5, 3.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (14, 'B03', 3.6, 3.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (15, 'B04', 4.7, 3.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (16, 'B05', 5.8, 3.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (17, 'B06', 6.9, 3.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (18, 'B07', 8.0, 3.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (19, 'B08', 9.1, 3.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (20, 'B09', 10.2, 3.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (21, 'B10', 11.3, 3.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (22, 'B11', 12.4, 3.4, 2, 1.1);
-- Fileira C
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (23, 'C01', 1.4, 7.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (24, 'C02', 2.5, 7.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (25, 'C03', 3.6, 7.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (26, 'C04', 4.7, 7.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (27, 'C05', 5.8, 7.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (28, 'C06', 6.9, 7.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (29, 'C07', 8.0, 7.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (30, 'C08', 9.1, 7.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (31, 'C09', 10.2, 7.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (32, 'C10', 11.3, 7.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (33, 'C11', 12.4, 7.4, 2, 1.1);

-- Fileira D
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (34, 'D01', 1.4, 10.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (35, 'D02', 2.5, 10.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (36, 'D03', 3.6, 10.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (37, 'D04', 4.7, 10.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (38, 'D05', 5.8, 10.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (39, 'D06', 6.9, 10.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (40, 'D07', 8.0, 10.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (41, 'D08', 9.1, 10.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (42, 'D09', 10.2, 10.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (43, 'D10', 11.3, 10.4, 2, 1.1);
INSERT INTO tabela_vaga (id_vaga, codigo, x_coord, y_coord, altura, largura) VALUES (44, 'D11', 12.4, 10.4, 2, 1.1);

--ANCHORS
INSERT INTO tabela_anchor (id_anchor, codigo, x_coord, y_coord) VALUES (1, 'A1', 0.0, 0.0);
INSERT INTO tabela_anchor (id_anchor, codigo, x_coord, y_coord) VALUES (2, 'A2', 15.0, 0.0);
INSERT INTO tabela_anchor (id_anchor, codigo, x_coord, y_coord) VALUES (3, 'A3', 0.0, 15.0);
INSERT INTO tabela_anchor (id_anchor, codigo, x_coord, y_coord) VALUES (4, 'A4', 15.0, 15.0);
INSERT INTO tabela_anchor (id_anchor, codigo, x_coord, y_coord) VALUES (5, 'A5', 0.0, 7.5);
INSERT INTO tabela_anchor (id_anchor, codigo, x_coord, y_coord) VALUES (6, 'A6', 15.0, 7.5);
INSERT INTO tabela_anchor (id_anchor, codigo, x_coord, y_coord) VALUES (7, 'A7', 7.5, 0.0);
INSERT INTO tabela_anchor (id_anchor, codigo, x_coord, y_coord) VALUES (8, 'A8', 7.5, 15.0);

--SELECTS
SELECT * FROM tabela_vaga;
SELECT * FROM tabela_moto;
SELECT * FROM tabela_ocupacao;
SELECT * FROM tabela_historico;
SELECT * FROM tabela_anchor;